### PR TITLE
Original novus nvd3 project

### PR DESCRIPTION
**Pull request by omnikron**
once adeven/adjust#1255 is merged this can also be merged - it changes back to the [original nvd3 project](www.github.com/novus/nvd3) instead of using adeven's fork thereof.

### CODE REVIEW

**Comment by voltechs** [comment]
Please do this soon! The code bases are out of date and conflicting. Pie charts and other charts don't work.

**Comment by omnikron** [comment]
@rapimo shall I merge this and release a new version on rubygems.org? it would mean a new major version as the nvd3 API has changed in a way that may break some charts.

**Comment by rapimo** [comment]
Yep make sure to increase the version

**Comment by omnikron** [comment]
note to self, don't delete the branch as other projects may be pointing to it

**Pull request merged**
